version: "3.9"

services:
  api:
    build:
      context: .
      args:
        BUILD_CONFIG: ${BUILD_CONFIG}
      dockerfile: Dockerfile
    container_name: "${CONTAINER_NAME}"
    ports:
      - "${HTTP_PORT}:80"
    networks:
      - internal_net

networks:
  internal_net:
